site_name: SkinsRestorerDOC
repo_url: https://github.com/xknat/SkinsRestorerDOC
pages:
- Home: index.md
- About: about.md
- Bugs: bugs.md
- Versions: versions.md
- Commands: commands.md
- Config: config.md

theme: readthedocs
